# Generated by Django 5.1.7 on 2026-05-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='realese_date',
            new_name='release_date',
        ),
    ]
