# Generated by Django 6.0.5 on 2026-06-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_realese_date_game_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='game',
        ),
        migrations.RemoveField(
            model_name='post',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplatform',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameslibrary',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gameplatform',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='gameslibrary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userplatform',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userplatform',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameComment',
        ),
        migrations.DeleteModel(
            name='GamePlatform',
        ),
        migrations.DeleteModel(
            name='GamesLibrary',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPlatform',
        ),
    ]
